theme: jekyll-theme-minimal
title: NIHR PIC South London
description: An interactive mapping tool to identify and analyse potential GP Participation Identification Centre (PIC) sites across South London, supporting inclusion in clinical research.
